server_cert_key_certificate: ((harbor-container-registry/server_cert_key.certificate))
server_cert_key_privatekey: ((harbor-container-registry/server_cert_key.private_key))
server_cert_ca: ((harbor-container-registry/server_cert_key.ca))
admin_password: ((harbor-container-registry/admin_password))
admin_password_for_smoketest: ((harbor-container-registry/admin_password))